import { Settled } from "./Settled";
import { SettledId } from "./SettledId";
import { GroupId } from "../group/GroupId";
import { UserId } from "../user/UserId";

export interface SettledData {
  groupId: GroupId;
  who: UserId;
  whom: UserId;
  amount: number;
}

export interface SettledRepository {
  // Create settlements generated by cash-flow minimization
  createSettlement(data: SettledData): Promise<Settled | null>;

  // Get a specific settlement
  getSettlementById(settledId: SettledId): Promise<Settled | null>;

  // All settlements for a group
  getSettlementsByGroup(groupId: GroupId): Promise<Settled[]>;

  // Pending settlements involving a user (optionally scoped to group)
  getPendingSettlementsByUser(
    userId: UserId,
    groupId?: GroupId
  ): Promise<Settled[]>;

  // Mark settlement as completed
  markAsSettled(settledId: SettledId): Promise<void>;

  // Delete settlement (rare: recalculation / rollback)
  deleteSettlement(settledId: SettledId): Promise<void>;

  // delete settlement 
  deleteSettlementByGroup(groupId: GroupId): Promise<void>;
}
