import { Suggestion } from "./Suggestion";
import { SuggestionId } from "./SuggestionId";
import { GroupId } from "../group/GroupId";
import { UserId } from "../user/UserId";

export interface SuggestionData {
  groupId: GroupId;
  who: UserId;
  whom: UserId;
  amount: number;
}

export interface SuggestionRepository {
  // Create settlements generated by cash-flow minimization
  createSuggestion(data: SuggestionData): Promise<Suggestion | null>;

  getSuggestionById(suggestionId: SuggestionId): Promise<Suggestion | null>;

  getSuggestionsByGroup(groupId: GroupId): Promise<Suggestion[]>;

  getSuggestionByIdAndGroup(
    groupId: GroupId,
    suggestionId: SuggestionId
  ): Promise<Suggestion | null>;

  getPendingSuggestionsByUser(
    userId: UserId,
    groupId?: GroupId
  ): Promise<Suggestion[]>;

  markAsSettled(suggestionId: SuggestionId): Promise<void>;

  deleteSuggestionsByGroup(groupId: GroupId): Promise<void>;
}
